### Do Not Remove This .yaml File!
trigger:
  branches:
    include:
    - master
pool:
  name: Azure Pipelines
steps:
- task: ms.advancedsecurity-tasks.codeql.init.AdvancedSecurity-Codeql-Init@1
  displayName: 'Initialize CodeQL'
  inputs:
    languages: javascript
    querysuite: 'security-extended'

- task: ms.advancedsecurity-tasks.codeql.enhance.AdvancedSecurity-Publish@1
  displayName: 'Publish Results'